# Spring
spring:
  config:
    import: 'aws-parameterstore:'

  datasource:
    #url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username:
    #password:
  sql:
    init:
      mode: never
  
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

aws:
  paramstore:
    enabled: true
    region: ap-northeast-3
    prefix: /config
    profileSeparator: _
    failFast: true


      
